const PROVIDERS={
  max:{name:"Max",short:"MAX",color:"#4f45e8",plans:{adfree:18.49,ads:10.99}},hulu:{name:"Hulu",short:"HU",color:"#1ce783",plans:{adfree:18.99,ads:9.99}},netflix:{name:"Netflix",short:"N",color:"#e50914",plans:{adfree:17.99,ads:7.99}},apple:{name:"Apple TV+",short:"TV+",color:"#eff1f3",text:"#111",plans:{adfree:12.99}},prime:{name:"Prime Video",short:"PV",color:"#1399e8",plans:{adfree:11.98,ads:8.99}},disney:{name:"Disney+",short:"D+",color:"#103b9b",plans:{adfree:18.99,ads:11.99}},paramount:{name:"Paramount+",short:"P+",color:"#1264e3",plans:{adfree:12.99,ads:7.99}},peacock:{name:"Peacock",short:"PE",color:"#111",plans:{adfree:16.99,ads:10.99}}
};
function sub(provider,adfree=true){return{provider,kind:"subscription",adfree}}
function rent(provider,price){return{provider,kind:"rent",price,adfree:true}}
function buy(provider,price){return{provider,kind:"buy",price,adfree:true}}
const DEMO_TITLES=[
  {id:1,title:"The Sopranos",type:"series",year:1999,rating:8.7,runtime:"6 seasons",genres:"Drama · Crime",match:98,colors:["#84745f","#211d1a"],synopsis:"New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life, seeking help from a therapist.",offers:[sub("max"),buy("apple",99.99)]},
  {id:2,title:"Severance",type:"series",year:2022,rating:8.7,runtime:"2 seasons",genres:"Drama · Mystery",match:96,colors:["#77968d","#172320"],synopsis:"Office workers whose memories have been surgically divided uncover a mystery at the heart of their company.",offers:[sub("apple")]},
  {id:3,title:"Dune: Part Two",type:"movie",year:2024,rating:8.5,runtime:"2h 46m",genres:"Sci-Fi · Adventure",match:94,colors:["#d27c43","#322017"],synopsis:"Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",offers:[sub("max"),rent("prime",3.99),rent("apple",4.99)]},
  {id:4,title:"Shōgun",type:"series",year:2024,rating:8.6,runtime:"1 season",genres:"Drama · History",match:93,colors:["#b12722","#23100f"],synopsis:"In Japan in 1600, Lord Yoshii Toranaga fights for his life as his enemies unite against him.",offers:[sub("hulu"),buy("apple",19.99)]},
  {id:5,title:"The Bear",type:"series",year:2022,rating:8.5,runtime:"4 seasons",genres:"Drama · Comedy",match:92,colors:["#3b7bb5","#101c26"],synopsis:"A young chef returns to Chicago to run his family's sandwich shop after a heartbreaking death.",offers:[sub("hulu"),buy("prime",19.99)]},
  {id:6,title:"Oppenheimer",type:"movie",year:2023,rating:8.1,runtime:"3h 1m",genres:"Drama · History",match:91,colors:["#dd6b2f","#17100c"],synopsis:"The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.",offers:[sub("prime"),rent("apple",5.99),rent("peacock",4.99)]},
  {id:7,title:"Stranger Things",type:"series",year:2016,rating:8.6,runtime:"4 seasons",genres:"Sci-Fi · Horror",match:89,colors:["#bc1f2a","#160b0e"],synopsis:"When a young boy vanishes, a small town uncovers secret experiments and supernatural forces.",offers:[sub("netflix")]},
  {id:8,title:"The Last of Us",type:"series",year:2023,rating:8.7,runtime:"2 seasons",genres:"Drama · Adventure",match:88,colors:["#5b6c46","#181b14"],synopsis:"A hardened survivor escorts a teenage girl across a post-apocalyptic United States.",offers:[sub("max"),buy("apple",24.99)]},
  {id:9,title:"Everything Everywhere All at Once",type:"movie",year:2022,rating:7.7,runtime:"2h 20m",genres:"Comedy · Sci-Fi",match:87,colors:["#9b55bc","#1b1020"],synopsis:"An overwhelmed immigrant mother must connect with parallel-universe versions of herself.",offers:[sub("paramount"),rent("prime",3.99),rent("apple",3.99)]},
  {id:10,title:"Succession",type:"series",year:2018,rating:8.9,runtime:"4 seasons",genres:"Drama · Comedy",match:95,colors:["#96744d","#1c1611"],synopsis:"The Roy family wrestles for control of their global media empire.",offers:[sub("max"),buy("prime",28.99)]},
  {id:11,title:"Ted Lasso",type:"series",year:2020,rating:8.8,runtime:"3 seasons",genres:"Comedy · Sport",match:90,colors:["#dfbc45","#203b59"],synopsis:"An optimistic American football coach is hired to manage a struggling English soccer team.",offers:[sub("apple")]},
  {id:12,title:"The Godfather",type:"movie",year:1972,rating:9.2,runtime:"2h 55m",genres:"Crime · Drama",match:97,colors:["#8f352e","#160d0c"],synopsis:"The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",offers:[sub("paramount"),rent("prime",3.99),rent("apple",3.99)]}
];
const REGIONS={US:["🇺🇸","United States","$"],IN:["🇮🇳","India","₹"],GB:["🇬🇧","United Kingdom","£"],CA:["🇨🇦","Canada","CA$"],AU:["🇦🇺","Australia","A$"]};
const monthOptions=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()+i);return{key:`${d.getFullYear()}-${d.getMonth()}`,label:d.toLocaleDateString("en-US",{month:"long",year:"numeric"})}});
const state={view:"discover",filter:"all",query:"",region:localStorage.getItem("cw-region")||"US",watchlist:JSON.parse(localStorage.getItem("cw-watchlist")||"[]"),activeMonth:monthOptions[0].key,optimizerMonth:monthOptions[0].key,mode:"adfree",owned:JSON.parse(localStorage.getItem("cw-owned")||"[]"),catalog:[...DEMO_TITLES],live:false,loading:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],sameId=(a,b)=>String(a)===String(b);
function persist(){localStorage.setItem("cw-watchlist",JSON.stringify(state.watchlist));localStorage.setItem("cw-owned",JSON.stringify(state.owned))}
function getTitle(id){return state.catalog.find(t=>sameId(t.id,id))||state.watchlist.find(e=>sameId(e.id,id))?.title||DEMO_TITLES.find(t=>sameId(t.id,id))}
function isAdded(id){return state.watchlist.some(e=>sameId(e.id,id))}
function initials(title){return title.split(/\s+/).filter(w=>!["the","a","at","of"].includes(w.toLowerCase())).slice(0,2).map(w=>w[0]).join("")}
function formatCost(value){return value===0?"Included":Number.isFinite(value)?`$${value.toFixed(2)}`:"—"}
function planPrice(key,mode){const p=PROVIDERS[key]?.plans;if(!p)return Infinity;return mode==="overall"?(p.ads??p.adfree):p.adfree}
function offerCost(o,mode=state.mode){if(o.kind==="free")return 0;if(o.kind==="subscription"||o.kind==="ads")return planPrice(o.provider,mode);return Number.isFinite(o.price)?o.price:Infinity}
function bestOffer(t,mode="adfree"){return[...(t.offers||[])].filter(o=>mode!=="adfree"||o.adfree!==false).sort((a,b)=>offerCost(a,mode)-offerCost(b,mode))[0]}
function providerLogo(key,large=false){const p=PROVIDERS[key];if(!p)return`<span class="${large?'big-logo':'provider-logo'} unknown-logo">?</span>`;return`<span class="${large?'big-logo':'provider-logo'}" style="background:${p.color};color:${p.text||'#fff'}">${p.short}</span>`}
function offerLogo(o,large=false){return o?.providerLogo?`<span class="${large?'big-logo':'provider-logo'} image-logo"><img src="${o.providerLogo}" alt=""></span>`:providerLogo(o?.provider,large)}
function posterStyle(t,backdrop=false){const image=backdrop?t.backdrop:t.poster;return`--poster-a:${t.colors[0]};--poster-b:${t.colors[1]};${image?`background-image:linear-gradient(0deg,rgba(0,0,0,.88),transparent 58%),url('${image}');background-size:cover;background-position:center;`:''}`}

function renderCards(){
  const query=state.query.trim().toLowerCase();
  const rows=state.catalog.filter(t=>(state.filter==="all"||t.type===state.filter)&&(!query||`${t.title} ${t.genres} ${t.year}`.toLowerCase().includes(query)));
  $("#resultKicker").textContent=state.loading?"SEARCHING THE LIVE CATALOG":query?`${rows.length} MATCH${rows.length===1?'':'ES'} FOUND`:state.live?"LIVE TRENDING CATALOG":"CURATED DEMONSTRATION";
  $("#resultTitle").textContent=query?`Results for “${state.query.trim()}”`:"Popular right now";
  $("#resultsGrid").innerHTML=rows.length?rows.map(t=>{
    const best=bestOffer(t),p=PROVIDERS[best?.provider],logos=[...new Map((t.offers||[]).map(o=>[o.providerId||o.provider,o])).values()].slice(0,3);
    const label=best?(best.kind==="subscription"||best.kind==="ads"?(p?.name||best.providerName):(Number.isFinite(best.price)?formatCost(best.price):(best.providerName||"View offers"))):"Check availability";
    return`<article class="title-card" data-id="${t.id}"><div class="poster" style="${posterStyle(t)}"><span class="match-badge">${t.match}% MATCH</span><button class="quick-add ${isAdded(t.id)?'added':''}" data-add="${t.id}">${isAdded(t.id)?'✓':'+'}</button>${t.poster?'':`<div class="poster-art">${initials(t.title)}</div>`}<div class="poster-copy"><small>${t.type}</small><strong>${t.title}</strong></div></div><div class="card-info"><h3>${t.title}</h3><div class="meta"><span>${t.year||'—'}</span><span>•</span><span>TMDB ${t.rating}</span><span>•</span><span>${t.runtime}</span></div><div class="availability"><div class="provider-stack">${logos.map(o=>offerLogo(o)).join('')}</div><span class="from-price">best <strong>${label}</strong></span></div></div></article>`
  }).join(""):`<div class="empty-state"><h3>${state.loading?'Searching…':'No titles found'}</h3><p>${state.loading?'Checking movies and series worldwide.':'Try a different title, genre, or year.'}</p></div>`
}
async function requestJson(url){const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(String(r.status));return r.json()}
function mergeTitle(title){const i=state.catalog.findIndex(t=>sameId(t.id,title.id));if(i>=0)state.catalog[i]=title;else state.catalog.unshift(title);const saved=state.watchlist.find(e=>sameId(e.id,title.id));if(saved)saved.title=title;persist();return title}
async function fetchFullTitle(title){if(!title?.live||!title.tmdbId)return title;try{const d=await requestJson(`api/title?id=${encodeURIComponent(title.tmdbId)}&type=${title.type==='series'?'tv':'movie'}&region=${state.region}`);return mergeTitle(d.result)}catch{toast("Live availability is temporarily unavailable");return title}}
let searchTimer=0,searchSequence=0;
async function liveSearch(query){const seq=++searchSequence;if(query.trim().length<2)return loadTrending();state.loading=true;renderCards();try{const d=await requestJson(`api/search?q=${encodeURIComponent(query.trim())}`);if(seq!==searchSequence)return;state.catalog=d.results;state.live=true}catch{if(seq!==searchSequence)return;state.catalog=[...DEMO_TITLES];state.live=false}finally{if(seq===searchSequence){state.loading=false;renderCards()}}}
async function loadTrending(){state.loading=true;renderCards();try{const d=await requestJson("api/trending");state.catalog=d.results;state.live=true}catch{state.catalog=[...DEMO_TITLES];state.live=false}finally{state.loading=false;renderCards()}}
async function addTitle(id){const existing=state.watchlist.find(e=>sameId(e.id,id));if(existing){state.watchlist=state.watchlist.filter(e=>!sameId(e.id,id));toast("Removed from your plan")}else{let title=getTitle(id);if(!title)return;if(title.live&&!(title.offers||[]).length)title=await fetchFullTitle(title);state.watchlist.push({id:title.id,month:state.activeMonth,title});toast("Added — cheapest plan recalculated")}persist();updateCount();renderCards();if(state.view==="plan")renderPlan();if(state.view==="optimizer")renderOptimizer()}
function updateCount(){$("#planCount").textContent=state.watchlist.length}
function setView(view){state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==="plan")renderPlan();if(view==="optimizer")renderOptimizer();window.scrollTo({top:0,behavior:"smooth"})}
function renderMonthControls(){$("#monthTabs").innerHTML=monthOptions.map(m=>`<button class="month-tab ${m.key===state.activeMonth?'active':''}" data-month="${m.key}">${m.label.split(' ')[0]} <small>${state.watchlist.filter(e=>e.month===m.key).length}</small></button>`).join('');$("#optimizerMonth").innerHTML=monthOptions.map(m=>`<option value="${m.key}">${m.label}</option>`).join('');$("#optimizerMonth").value=state.optimizerMonth}

function optimize(titles,mode,owned){
  if(!titles.length)return{providers:[],total:0,covered:[],rentals:[],uncovered:[]};
  const keys=[...new Set(titles.flatMap(t=>(t.offers||[]).filter(o=>o.provider&&o.kind==="subscription"&&(mode!=="adfree"||PROVIDERS[o.provider]?.plans.adfree!=null)).map(o=>o.provider)))];let best=null;
  for(let mask=0;mask<(1<<keys.length);mask++){const selected=keys.filter((_,i)=>mask&(1<<i)),covered=titles.filter(t=>(t.offers||[]).some(o=>o.kind==="subscription"&&selected.includes(o.provider))),rentals=titles.filter(t=>!covered.includes(t)).map(t=>({title:t,offer:(t.offers||[]).filter(o=>o.kind!=="subscription"&&Number.isFinite(o.price)).sort((a,b)=>a.price-b.price)[0]})),monthly=selected.reduce((s,p)=>s+(owned.includes(p)?0:planPrice(p,mode)),0),total=Math.round((monthly+rentals.reduce((s,r)=>s+(r.offer?.price??999),0))*100)/100;if(!best||total<best.total||(total===best.total&&selected.length<best.providers.length))best={providers:selected,total,covered,rentals}}
  return{...best,uncovered:best.rentals.filter(r=>!r.offer)}
}
function renderPlan(){
  renderMonthControls();const entries=state.watchlist.filter(e=>e.month===state.activeMonth),titles=entries.map(e=>getTitle(e.id)).filter(Boolean),rec=optimize(titles,"adfree",state.owned);
  $("#planSummary").innerHTML=`<div class="summary-card accent"><span>Recommended subscriptions</span><strong>${rec.providers.length?rec.providers.map(p=>PROVIDERS[p].name).join(' + '):'No priced subscription selected'}</strong></div><div class="summary-card"><span>Titles this month</span><strong>${titles.length}</strong></div><div class="summary-card"><span>Estimated cost</span><strong>${rec.total>=999?'Check offers':formatCost(rec.total)}</strong></div>`;
  $("#watchlist").innerHTML=entries.length?entries.map(e=>{const t=getTitle(e.id),b=bestOffer(t),p=PROVIDERS[b?.provider],best=b?(p?.name||b.providerName||"Provider")+(Number.isFinite(offerCost(b,"adfree"))?` · ${formatCost(offerCost(b,"adfree"))}${b.kind==='subscription'?'/mo':''}`:" · check price"):"Availability not found";return`<div class="watch-row"><div class="mini-poster" style="${posterStyle(t)}">${t.poster?'':initials(t.title)}</div><div class="watch-title"><strong>${t.title}</strong><small>${t.year||'—'} · ${t.type}</small></div><select data-move="${t.id}">${monthOptions.map(m=>`<option value="${m.key}" ${e.month===m.key?'selected':''}>${m.label}</option>`).join('')}</select><div class="best-option"><span>Cheapest ad-free</span><strong>${best}</strong></div><button class="remove-btn" data-remove="${t.id}">×</button></div>`}).join(''):`<div class="empty-state"><h3>Nothing planned for this month</h3><p>Discover a title and use + to add it.</p><button class="primary-btn" data-view-jump="discover">Find something to watch</button></div>`
}
function renderOwned(){$("#ownedServices").innerHTML=Object.entries(PROVIDERS).map(([k,p])=>`<label class="service-check"><span>${providerLogo(k)} ${p.name}</span><input type="checkbox" data-owned="${k}" ${state.owned.includes(k)?'checked':''}></label>`).join('')}
function renderOptimizer(){
  renderMonthControls();renderOwned();const entries=state.watchlist.filter(e=>e.month===state.optimizerMonth),titles=entries.map(e=>getTitle(e.id)).filter(Boolean),r=optimize(titles,state.mode,state.owned),budget=Number($("#budgetInput").value)||0,covered=titles.length-r.uncovered.length,pct=titles.length?Math.round(covered/titles.length*100):0,total=r.total>=999?null:r.total;
  $("#optimizationResult").innerHTML=titles.length?`<div class="rec-header"><div><span class="section-kicker">BEST VALUE COMBINATION</span><h2>Your recommended plan</h2><p>Calculated across available providers for ${REGIONS[state.region][1]}.</p></div><div class="total-cost"><small>Estimated total</small><strong>${total===null?'—':formatCost(total)}</strong><span>for this month</span></div></div><div class="coverage-bar"><div class="coverage-label"><span>Priced plan coverage</span><strong>${covered} of ${titles.length} titles</strong></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="recommendation-list">${r.providers.map(k=>{const p=PROVIDERS[k],count=titles.filter(t=>(t.offers||[]).some(o=>o.kind==='subscription'&&o.provider===k)).length,free=state.owned.includes(k);return`<div class="provider-rec">${providerLogo(k,true)}<div><h3>${p.name} — ${state.mode==='adfree'?'Ad-free':'Lowest-price'} plan</h3><p>Covers ${count} title${count===1?'':'s'}${free?' · Already owned':''}</p></div><div class="provider-cost">${free?'$0.00':formatCost(planPrice(k,state.mode))}<small>${free?'owned':'estimated per month'}</small></div></div>`}).join('')}${r.rentals.map(x=>x.offer?`<div class="provider-rec">${offerLogo(x.offer,true)}<div><h3>Rent ${x.title.title}</h3><p>Cheapest one-time option</p></div><div class="provider-cost">${formatCost(x.offer.price)}<small>one-time</small></div></div>`:`<div class="provider-rec"><span class="big-logo unknown-logo">!</span><div><h3>${x.title.title}</h3><p>Availability found; exact price requires the pricing partner.</p></div><div class="provider-cost">—<small>check provider</small></div></div>`).join('')}</div><div class="explanation ${total!==null&&total>budget?'over-budget':''}">${total===null?'Some exact prices are unavailable, so no false total is shown.':total<=budget?`✓ Within your $${budget.toFixed(0)} budget by $${(budget-total).toFixed(2)}.`:`$${(total-budget).toFixed(2)} over budget. Move titles to another month.`} Confirm prices with the provider.</div>`:`<div class="empty-state"><h3>Your optimizer is ready</h3><p>Add titles to this month and the best combination will appear here.</p><button class="primary-btn" data-view-jump="discover">Discover titles</button></div>`
}
async function openDetail(id){
  let t=getTitle(id);if(!t)return;$("#detailContent").innerHTML=`<div class="detail-loading"><span class="loader"></span><h3>Checking ${t.title}</h3><p>Loading current availability for ${REGIONS[state.region][1]}…</p></div>`;$("#detailModal").classList.add('open');$("#detailModal").setAttribute('aria-hidden','false');if(t.live)t=await fetchFullTitle(t);const month=monthOptions.find(m=>m.key===state.activeMonth),offers=t.offers||[],rows=offers.length?offers.map((o,i)=>{const p=PROVIDERS[o.provider],price=o.kind==='subscription'?planPrice(o.provider,'adfree'):o.price,label=o.kind==='ads'?'with ads':o.kind;return`<div class="offer">${offerLogo(o,true)}<div><strong>${p?.name||o.providerName||'Provider'}</strong><div class="offer-type">${label}${i===0?' · available now':''}</div></div><span class="offer-price">${Number.isFinite(price)?formatCost(price)+(o.kind==='subscription'?'/mo':''):'Check price'}</span>${t.providerLink?`<a href="${t.providerLink}" target="_blank" rel="noopener">View ↗</a>`:'<span></span>'}</div>`}).join(''):`<div class="empty-state compact"><h3>No offer found</h3><p>Availability may not be reported for this region.</p></div>`;
  const imdb=t.imdbRating?`<span class="imdb-score"><b>IMDb</b> ${t.imdbRating}/10${t.imdbVotes?` · ${t.imdbVotes} votes`:''}</span>`:t.imdbId?`<a class="imdb-score" href="https://www.imdb.com/title/${t.imdbId}/" target="_blank" rel="noopener"><b>IMDb</b> View rating ↗</a>`:'';
  $("#detailContent").innerHTML=`<div class="detail-hero" style="${posterStyle(t,true)}"><div><span class="section-kicker">${t.match}% MATCH · ${t.type.toUpperCase()}</span><h2 id="detailTitle">${t.title}</h2><div class="meta"><span>${t.year||'—'}</span><span>•</span><span>TMDB ${t.rating}</span><span>•</span><span>${t.runtime}</span><span>•</span><span>${t.genres}</span></div>${imdb}<p>${t.synopsis}</p></div></div><div class="detail-body"><h3>Where to watch in ${REGIONS[state.region][1]}</h3><div class="offer-list">${rows}</div>${t.live?'<p class="data-credit">Availability powered by JustWatch via TMDB · IMDb rating shown only when separately sourced.</p>':''}<button class="primary-btn add-plan-btn" data-add="${t.id}">${isAdded(t.id)?'Remove from plan':`Add to ${month.label} plan`} →</button></div>`
}
function closeDetail(){$("#detailModal").classList.remove('open');$("#detailModal").setAttribute('aria-hidden','true')}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function updateRegion(){const r=REGIONS[state.region];$("#regionFlag").textContent=r[0];$("#heroRegion").textContent=r[1];$("#regionPicker").value=state.region;localStorage.setItem("cw-region",state.region);renderCards()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)return setView(nav.dataset.view);const jump=e.target.closest('[data-view-jump]');if(jump)return setView(jump.dataset.viewJump);const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addTitle(add.dataset.add);if(add.closest('.detail-modal'))closeDetail();return}const card=e.target.closest('.title-card');if(card)return openDetail(card.dataset.id);const filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));return renderCards()}const month=e.target.closest('[data-month]');if(month){state.activeMonth=month.dataset.month;return renderPlan()}const remove=e.target.closest('[data-remove]');if(remove)return addTitle(remove.dataset.remove);const mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.dataset.mode;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b===mode));return renderOptimizer()}if(e.target.id==='detailModal'||e.target.closest('.modal-close'))closeDetail()});
document.addEventListener('change',e=>{if(e.target.matches('[data-move]')){const item=state.watchlist.find(x=>sameId(x.id,e.target.dataset.move));item.month=e.target.value;persist();toast('Title moved — plan recalculated');renderPlan()}if(e.target.matches('[data-owned]')){const key=e.target.dataset.owned;state.owned=e.target.checked?[...new Set([...state.owned,key])]:state.owned.filter(x=>x!==key);persist();renderOptimizer()}});
$("#searchInput").addEventListener('input',e=>{state.query=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>liveSearch(state.query),300)});$("#regionPicker").addEventListener('change',e=>{state.region=e.target.value;updateRegion();toast(`Region changed to ${REGIONS[state.region][1]}`);if(state.view==='discover')loadTrending()});$("#optimizerMonth").addEventListener('change',e=>{state.optimizerMonth=e.target.value;renderOptimizer()});$("#budgetInput").addEventListener('input',renderOptimizer);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setView('discover');$("#searchInput").focus()}if(e.key==='Escape')closeDetail()});
updateCount();updateRegion();renderMonthControls();loadTrending();
